FROM mcr.microsoft.com/devcontainers/base:ubuntu24.04

RUN apt-get update

RUN apt-get -y upgrade

RUN sudo apt-get -y install gcc git wget make libncurses-dev flex bison gperf

RUN sudo apt-get -y install libgtk-3-dev

RUN sudo apt-get -y install git-lfs
